import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-24T23:29:19.402Z

test.describe('Landing Page Verification', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:12440');

    // Navigate to http://127.0.0.1:12440
    await page.goto('http://127.0.0.1:12440');

    // Take a snapshot of the page
    await expect(page).toHaveScreenshot();

    // Assert the page contains the main heading
    await expect(page.getByText('the main heading')).toBeVisible();

  });
});
