import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-01T11:39:53.486Z

test.describe('Landing Page Verification', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Take a snapshot of the page
    await expect(page).toHaveScreenshot();

    // Assert the page contains the main heading
    await expect(page.getByText('the main heading')).toBeVisible();

  });
});
