import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-25T08:05:08.793Z

test.describe('Scenario: Landing page opens the operations console', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:11019');

    // Navigate to http://127.0.0.1:11019
    await page.goto('http://127.0.0.1:11019');

    // Assert page contains "Simulate a real QA control room."
    await expect(page.getByText('Simulate a real QA control room.')).toBeVisible();

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Assert page contains "Sign In"
    await expect(page.getByText('Sign In')).toBeVisible();

  });
});
