import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-17T09:51:46.678Z

test.describe('Scenario: Run Tests button works as expected', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Click "Run Tests"
    await page.getByRole('button', { name: 'Run Tests' }).or(page.getByRole('link', { name: 'Run Tests' })).click();

    // Assert page contains "Tests queued successfully."
    await expect(page.getByText('Tests queued successfully.')).toBeVisible();

  });
});
