import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-02T02:16:05.188Z

test.describe('Scenario: Landing page loads with correct title and heading', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Assert page contains "TestingQA"
    await expect(page.getByText('TestingQA')).toBeVisible();

  });
});
