import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-19T11:15:18.335Z

test.describe('Scenario: Dashboard renders with seeded tasks correctly', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:6000/');

    // Navigate to http://127.0.0.1:6000/
    await page.goto('http://127.0.0.1:6000/');

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Click "Sign In" (using seeded credentials if visible)
    await page.getByRole('button', { name: 'Sign In' }).or(page.getByRole('link', { name: 'Sign In' })).click();

    // Assert page contains "Audit checkout release gate"
    await expect(page.getByText('Audit checkout release gate')).toBeVisible();

    // Assert page contains "Review the checkout smoke pack, confirm payment widget telemetry, and prepare the rollback note before the release"
    await expect(page.getByText('Review the checkout smoke pack, confirm payment widget telemetry, and prepare the rollback note before the release')).toBeVisible();

  });
});
