import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-02T02:16:05.189Z

test.describe('Scenario: Authentication page spec file references correct route', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Assert page contains "TestingQA"
    await expect(page.getByText('TestingQA')).toBeVisible();

    // Assert page contains "A sample application for validating SentinelQA automated testing pipeline. This page serves as the test target for end-to-end browser tests."
    await expect(page.getByText('A sample application for validating SentinelQA automated testing pipeline. This page serves as the test target for end-to-end browser tests.')).toBeVisible();

  });
});
