import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-02T09:19:44.330Z

test.describe('Scenario 4: Verify Login Form Text', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173/auth
    await page.goto('http://localhost:5173/auth');

    // Assert the page contains "Login to your account" (assuming this is the text within the login form based on past plans)
    await expect(page.getByText('Login to your account" (assuming this is the text within the login form based on past plans)')).toBeVisible();

  });
});
