import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-18T15:00:46.682Z

test.describe('Scenario: Dashboard renders without broken JSX (unbalanced tags fixed)', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173
    await page.goto('http://127.0.0.1:4173');

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Assert page contains "Simulate a real QA control room."
    await expect(page.getByText('Simulate a real QA control room.')).toBeVisible();

    // Assert page contains "Open operations console"
    await expect(page.getByText('Open operations console')).toBeVisible();

  });
});
