import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-18T04:52:08.470Z

test.describe('Scenario: Launch the TestingQA control surface', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173
    await page.goto('http://127.0.0.1:4173');

    // Assert page contains "TestingQA"
    await expect(page.getByText('TestingQA')).toBeVisible();

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Assert page contains "Sign In"
    await expect(page.getByText('Sign In')).toBeVisible();

  });
});
