import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-19T10:50:50.470Z

test.describe('Scenario: Login form heading and content remain correct', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:5600/');

    // Navigate to http://127.0.0.1:5600/
    await page.goto('http://127.0.0.1:5600/');

    // Click "Sign In"
    await page.getByRole('button', { name: 'Sign In' }).or(page.getByRole('link', { name: 'Sign In' })).click();

    // Assert page contains "Sign In"
    await expect(page.getByText('Sign In')).toBeVisible();

    // Assert page does not contain "Simulate a real QA control room."
    // TODO: Assert page does not contain "Simulate a real QA control room."

  });
});
