import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-16T08:40:51.255Z

test.describe('Scenario: Authentication page route is accessible and contains login form', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173/auth
    await page.goto('http://127.0.0.1:4173/auth');

    // Assert page contains "a login form"
    await expect(page.getByText('a login form')).toBeVisible();

  });
});
