import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-17T10:24:50.219Z

test.describe('Scenario: Landing Page Displays Correct Title and Heading', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Assert page contains "TestingQA"
    await expect(page.getByText('TestingQA')).toBeVisible();

  });
});
