import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-02T09:17:04.748Z

test.describe('Scenario: Verify Architecture page renders correctly', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173/architecture
    await page.goto('http://localhost:5173/architecture');

    // Assert page contains "Architecture — MindFlayer"
    await expect(page.getByText('Architecture — MindFlayer')).toBeVisible();

    // Assert page contains "Auto-generated architecture diagram"
    await expect(page.getByText('Auto-generated architecture diagram')).toBeVisible();

  });
});
