import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-25T08:05:08.794Z

test.describe('Scenario: Sign in and open the task board', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:11019');

    // Navigate to http://127.0.0.1:11019
    await page.goto('http://127.0.0.1:11019');

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Fill "admin@test.com" into "Email"
    await page.getByLabel('"Email"').or(page.getByPlaceholder('"Email"')).fill('admin@test.com');

    // Fill "admin123" into "Password"
    await page.getByLabel('"Password"').or(page.getByPlaceholder('"Password"')).fill('admin123');

    // Click "Sign In"
    await page.getByRole('button', { name: 'Sign In' }).or(page.getByRole('link', { name: 'Sign In' })).click();

    // Assert page contains "Release Command Center"
    await expect(page.getByText('Release Command Center')).toBeVisible();

    // Assert page contains "Audit checkout release gate"
    await expect(page.getByText('Audit checkout release gate')).toBeVisible();

  });
});
