import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-26T08:24:32.070Z

test.describe('Scenario: Dashboard renders without broken JSX tags (unbalanced tags fixed)', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173
    await page.goto('http://127.0.0.1:4173');

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Assert page contains no raw `<` or `>` characters outside code blocks (i.e., no malformed JSX output)
    await expect(page.getByText('no raw `<` or `>` characters outside code blocks (i.e., no malformed JSX output)')).toBeVisible();

  });
});
