import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-24T12:39:25.524Z

test.describe('Scenario 5: Verify the original login form heading', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to `http://localhost:5173/login`
    await page.goto('http://localhost:5173/`http://localhost:5173/login`');

    // Assert page contains "Sign In"
    await expect(page.getByText('Sign In')).toBeVisible();

  });
});
