import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-25T07:35:26.674Z

test.describe('Scenario: Landing page loads with operations console entry', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4243');

    // Navigate to http://127.0.0.1:4243
    await page.goto('http://127.0.0.1:4243');

    // Assert page contains "Simulate a real QA control room."
    await expect(page.getByText('Simulate a real QA control room.')).toBeVisible();

    // Assert page contains "Open operations console"
    await expect(page.getByText('Open operations console')).toBeVisible();

  });
});
