import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-17T10:18:13.645Z

test.describe('Scenario: Task creation and validation retains original required fields', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Click "Create new task"
    await page.getByRole('button', { name: 'Create new task' }).or(page.getByRole('link', { name: 'Create new task' })).click();

    // Assert page contains "Title"
    await expect(page.getByText('Title')).toBeVisible();

    // Assert page contains "Description"
    await expect(page.getByText('Description')).toBeVisible();

    // Assert page contains "Priority"
    await expect(page.getByText('Priority')).toBeVisible();

    // Assert page contains "Assignee"
    await expect(page.getByText('Assignee')).toBeVisible();

    // Assert page contains "Create Task"
    await expect(page.getByText('Create Task')).toBeVisible();

  });
});
