import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-05-31T16:51:55.289Z

test.describe('Scenario: Landing page loads', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to /
    await page.goto('http://localhost:5173/');

    // Assert page contains "Dashboard"
    await expect(page.getByText('Dashboard')).toBeVisible();

  });
});
