import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-18T15:06:00.873Z

test.describe('Scenario: Verify run tests button is present and clickable', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to `/`
    await page.goto('http://localhost:5173/`/`');

    // Click "Run Tests"
    await page.getByRole('button', { name: 'Run Tests' }).or(page.getByRole('link', { name: 'Run Tests' })).click();

    // Assert page contains "Tests queued successfully."
    await expect(page.getByText('Tests queued successfully.')).toBeVisible();

  });
});
