import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-16T08:40:51.254Z

test.describe('Scenario: Landing page loads with correct title and heading', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173
    await page.goto('http://127.0.0.1:4173');

    // Assert page contains "TestingQA"
    await expect(page.getByText('TestingQA')).toBeVisible();

  });
});
