import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-16T09:44:54.919Z

test.describe('Scenario: Run Tests button is present and functional', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173
    await page.goto('http://127.0.0.1:4173');

    // Click "Run Tests"
    await page.getByRole('button', { name: 'Run Tests' }).or(page.getByRole('link', { name: 'Run Tests' })).click();

    // Assert page contains "Tests queued successfully."
    await expect(page.getByText('Tests queued successfully.')).toBeVisible();

  });
});
