import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-18T04:52:08.471Z

test.describe('Scenario: Verify the post-login operations view', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173#/console
    await page.goto('http://127.0.0.1:4173#/console');

    // Assert page contains "Create work item"
    await expect(page.getByText('Create work item')).toBeVisible();

    // Assert page contains "Activity feed"
    await expect(page.getByText('Activity feed')).toBeVisible();

  });
});
