import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-16T10:16:55.572Z

test.describe('Scenario: Landing page title and core content remain unchanged', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173
    await page.goto('http://127.0.0.1:4173');

    // Assert page contains "TestingQA"
    await expect(page.getByText('TestingQA')).toBeVisible();

    // Assert page contains "A sample application for validating SentinelQA automated testing pipeline"
    await expect(page.getByText('A sample application for validating SentinelQA automated testing pipeline')).toBeVisible();

  });
});
