import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-17T04:11:56.949Z

test.describe('Scenario: Dashboard renders with correct structure after login', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Assert page contains "Simulate a real QA control room."
    await expect(page.getByText('Simulate a real QA control room.')).toBeVisible();

    // Assert page contains "Audit checkout release gate"
    await expect(page.getByText('Audit checkout release gate')).toBeVisible();

  });
});
