import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-04T11:58:57.370Z

test.describe('Scenario 1: Landing Page Verification', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Assert the page contains the main heading
    await expect(page.getByText('the main heading')).toBeVisible();

  });
});
