import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-02T09:17:04.749Z

test.describe('Scenario: Verify Explorer page renders correctly', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173/explorer
    await page.goto('http://localhost:5173/explorer');

    // Assert page contains "Explorer — MindFlayer"
    await expect(page.getByText('Explorer — MindFlayer')).toBeVisible();

    // Assert page contains "Interactive dependency graph with comments and code snippets"
    await expect(page.getByText('Interactive dependency graph with comments and code snippets')).toBeVisible();

  });
});
