import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-17T10:18:13.645Z

test.describe('Scenario: Seed tasks include original release gate task', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Assert page contains "Audit checkout release gate"
    await expect(page.getByText('Audit checkout release gate')).toBeVisible();

    // Assert page contains "Review the checkout smoke pack, confirm payment widget telemetry, and prepare the rollback note before the release"
    await expect(page.getByText('Review the checkout smoke pack, confirm payment widget telemetry, and prepare the rollback note before the release')).toBeVisible();

    // Assert page contains "High"
    await expect(page.getByText('High')).toBeVisible();

  });
});
