import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-25T08:19:54.907Z

test.describe('Scenario: Verify operations console button is present and clickable', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to `/`
    await page.goto('http://localhost:5173/`/`');

    // Assert page contains "Open operations console" button
    await expect(page.getByText('Open operations console" button')).toBeVisible();

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Assert navigation to operations console route (if applicable)
    // TODO: Assert navigation to operations console route (if applicable)

  });
});
