import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-18T15:06:00.872Z

test.describe('Scenario: Verify login form heading and content', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to `/login`
    await page.goto('http://localhost:5173/`/login`');

    // Assert page contains "Sign In"
    await expect(page.getByText('Sign In')).toBeVisible();

    // Assert page contains "TestingQA demo target"
    await expect(page.getByText('TestingQA demo target')).toBeVisible();

  });
});
