import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-25T07:35:26.674Z

test.describe('Scenario: Create a new task and verify it appears in task list', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4243');

    // Navigate to http://127.0.0.1:4243
    await page.goto('http://127.0.0.1:4243');

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Type "admin@test.com" into input with name "email"
    await page.getByLabel('input with name "email"').or(page.getByPlaceholder('input with name "email"')).fill('admin@test.com');

    // Type "admin123" into input with name "password"
    await page.getByLabel('input with name "password"').or(page.getByPlaceholder('input with name "password"')).fill('admin123');

    // Click "Sign In"
    await page.getByRole('button', { name: 'Sign In' }).or(page.getByRole('link', { name: 'Sign In' })).click();

    // Type "Investigate staging checkout regression" into input with name "title"
    await page.getByLabel('input with name "title"').or(page.getByPlaceholder('input with name "title"')).fill('Investigate staging checkout regression');

    // Type "Capture the checkout flow and confirm the redirect after payment." into input with name "description"
    await expect(page).toHaveScreenshot();

    // Click "Create task"
    await page.getByRole('button', { name: 'Create task' }).or(page.getByRole('link', { name: 'Create task' })).click();

    // Assert page contains "Task created"
    await expect(page.getByText('Task created')).toBeVisible();

    // Assert page contains "Investigate staging checkout regression"
    await expect(page.getByText('Investigate staging checkout regression')).toBeVisible();

  });
});
