import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-16T10:10:01.533Z

test.describe('Scenario: Login view renders with original heading and structure', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173/#/login
    await page.goto('http://127.0.0.1:4173/#/login');

    // Assert page contains "Sign In"
    await expect(page.getByText('Sign In')).toBeVisible();

    // Assert page contains `<div class="login-form">` (via DOM inspection or fallback text match)
    await expect(page.getByText('`<div class="login-form">` (via DOM inspection or fallback text match)')).toBeVisible();

  });
});
