import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-26T10:29:52.669Z

test.describe('Scenario: Verify "Run Tests" button functionality', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to `/`
    await page.goto('http://localhost:5173/`/`');

    // Click "Run Tests"
    await page.getByRole('button', { name: 'Run Tests' }).or(page.getByRole('link', { name: 'Run Tests' })).click();

    // Assert page contains "Tests queued successfully." status message
    await expect(page.getByText('Tests queued successfully." status message')).toBeVisible();

  });
});
