import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-17T10:24:50.220Z

test.describe('Scenario: Authentication Page Contains Login Form', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173/auth
    await page.goto('http://localhost:5173/auth');

    // Assert page contains "a login form"
    await expect(page.getByText('a login form')).toBeVisible();

  });
});
