import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-16T09:52:53.724Z

test.describe('Scenario: Landing page displays original descriptive paragraph', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173
    await page.goto('http://127.0.0.1:4173');

    // Assert page contains "A sample application for validating SentinelQA automated testing pipeline. This page serves as the test target for end-to-end browser tests."
    await expect(page.getByText('A sample application for validating SentinelQA automated testing pipeline. This page serves as the test target for end-to-end browser tests.')).toBeVisible();

  });
});
