import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-04T11:58:57.371Z

test.describe('Scenario 5: Correct Text Assertion for Landing Page', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Assert the page contains "TestingQA"
    await expect(page.getByText('TestingQA')).toBeVisible();

  });
});
