import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-01T18:20:57.305Z

test.describe('Scenario: Run Tests button is present and functional', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Click "Run Tests"
    await page.getByRole('button', { name: 'Run Tests' }).or(page.getByRole('link', { name: 'Run Tests' })).click();

    // Assert page contains "Tests queued successfully."
    await expect(page.getByText('Tests queued successfully.')).toBeVisible();

  });
});
