import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-19T10:50:50.470Z

test.describe('Scenario: Dashboard renders with correct seeded task structure', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:5600/');

    // Navigate to http://127.0.0.1:5600/
    await page.goto('http://127.0.0.1:5600/');

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Assert page contains "Audit checkout release gate"
    await expect(page.getByText('Audit checkout release gate')).toBeVisible();

    // Assert page contains "Review the checkout smoke pack, confirm payment widget telemetry, and prepare the rollback note before the release"
    await expect(page.getByText('Review the checkout smoke pack, confirm payment widget telemetry, and prepare the rollback note before the release')).toBeVisible();

  });
});
