import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-02T09:19:44.330Z

test.describe('Scenario 2: Authentication Page Verification', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173/auth
    await page.goto('http://localhost:5173/auth');

    // Take a snapshot of the page
    await expect(page).toHaveScreenshot();

    // Assert the page contains a login form
    await expect(page.getByText('a login form')).toBeVisible();

  });
});
