import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-02T09:17:04.749Z

test.describe('Scenario: Verify Hotspots page renders correctly', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173/hotspots
    await page.goto('http://localhost:5173/hotspots');

    // Assert page contains "Hotspots — MindFlayer"
    await expect(page.getByText('Hotspots — MindFlayer')).toBeVisible();

    // Assert page contains "Git change frequency heatmap"
    await expect(page.getByText('Git change frequency heatmap')).toBeVisible();

  });
});
