import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-18T04:52:08.471Z

test.describe('Scenario: Sign in with the seeded admin account', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173#/login
    await page.goto('http://127.0.0.1:4173#/login');

    // Type "admin@test.com" into "Email"
    await page.getByLabel('"Email"').or(page.getByPlaceholder('"Email"')).fill('admin@test.com');

    // Type "admin123" into "Password"
    await page.getByLabel('"Password"').or(page.getByPlaceholder('"Password"')).fill('admin123');

    // Click "Sign In"
    await page.getByRole('button', { name: 'Sign In' }).or(page.getByRole('link', { name: 'Sign In' })).click();

    // Assert page contains "Audit checkout release gate"
    await expect(page.getByText('Audit checkout release gate')).toBeVisible();

  });
});
