import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-18T15:05:00.977Z

test.describe('Scenario: Login view renders with correct structure and target element', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173
    await page.goto('http://127.0.0.1:4173');

    // Assert page contains "Sign In"
    await expect(page.getByText('Sign In')).toBeVisible();

  });
});
