import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-04T11:58:57.371Z

test.describe('Scenario 3: Landing Page Snapshot', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Take a snapshot of the page
    await expect(page).toHaveScreenshot();

  });
});
