import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-19T11:15:18.333Z

test.describe('Scenario: Landing page title and core content remain unchanged', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:6000/');

    // Navigate to http://127.0.0.1:6000/
    await page.goto('http://127.0.0.1:6000/');

    // Assert page contains "TestingQA"
    await expect(page.getByText('TestingQA')).toBeVisible();

    // Assert page contains "A sample application for validating SentinelQA automated testing pipeline"
    await expect(page.getByText('A sample application for validating SentinelQA automated testing pipeline')).toBeVisible();

  });
});
