import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-02T09:19:44.330Z

test.describe('Scenario 3: Verify Main Heading Text', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Assert the page contains "Dashboard Overview" (assuming this is the main heading based on past plans)
    await expect(page.getByText('Dashboard Overview" (assuming this is the main heading based on past plans)')).toBeVisible();

  });
});
