import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-17T09:51:46.679Z

test.describe('Scenario: Login form renders with correct heading and structure', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Click "Sign In"
    await page.getByRole('button', { name: 'Sign In' }).or(page.getByRole('link', { name: 'Sign In' })).click();

    // Assert page contains "Sign In"
    await expect(page.getByText('Sign In')).toBeVisible();

  });
});
