import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-02T02:17:33.178Z

test.describe('Scenario: mindflayer.config.json contains mandatory smoke tests', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Assert page contains "TestingQA"
    await expect(page.getByText('TestingQA')).toBeVisible();

    // Click "Run Tests"
    await page.getByRole('button', { name: 'Run Tests' }).or(page.getByRole('link', { name: 'Run Tests' })).click();

    // Assert page contains "Tests queued successfully."
    await expect(page.getByText('Tests queued successfully.')).toBeVisible();

  });
});
