import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-16T10:10:01.533Z

test.describe('Scenario: Dashboard route renders with correct structure and original task data', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173/#/dashboard
    await page.goto('http://127.0.0.1:4173/#/dashboard');

    // Assert page contains "Audit checkout release gate"
    await expect(page.getByText('Audit checkout release gate')).toBeVisible();

    // Assert page contains "Review the checkout smoke pack, confirm payment widget telemetry, and prepare the rollback note before the release"
    await expect(page.getByText('Review the checkout smoke pack, confirm payment widget telemetry, and prepare the rollback note before the release')).toBeVisible();

  });
});
