import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-17T10:18:13.645Z

test.describe('Scenario: Dashboard renders with original task structure and filter options', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Assert page contains "Simulate a real QA control room."
    await expect(page.getByText('Simulate a real QA control room.')).toBeVisible();

    // Assert page contains "All"
    await expect(page.getByText('All')).toBeVisible();

    // Assert page contains "Pending"
    await expect(page.getByText('Pending')).toBeVisible();

    // Assert page contains "In Progress"
    await expect(page.getByText('In Progress')).toBeVisible();

    // Assert page contains "Completed"
    await expect(page.getByText('Completed')).toBeVisible();

  });
});
