import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-26T01:51:20.823Z

test.describe('Scenario: Login view uses correct container ID and preserves original structure', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4173');

    // Navigate to http://127.0.0.1:4173
    await page.goto('http://127.0.0.1:4173');

    // Assert page contains "Sign In"
    await expect(page.getByText('Sign In')).toBeVisible();

    // Assert page contains `<div class="login-form">` (via DOM inspection if needed, but prefer visible text)
    await expect(page.getByText('`<div class="login-form">` (via DOM inspection if needed, but prefer visible text)')).toBeVisible();

    // Assert page contains "TestingQA demo target" (eyebrow text from new landing) — *Note: This is ambiguous; prefer asserting original "Sign In" text which was present in original login.js*
    await expect(page.getByText('TestingQA demo target" (eyebrow text from new landing) — *Note: This is ambiguous; prefer asserting original "Sign In" text which was present in original login.js*')).toBeVisible();

  });
});
