import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-25T07:35:26.674Z

test.describe('Scenario: Login with valid credentials grants access to task board', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:4243');

    // Navigate to http://127.0.0.1:4243
    await page.goto('http://127.0.0.1:4243');

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Type "admin@test.com" into input with name "email"
    await page.getByLabel('input with name "email"').or(page.getByPlaceholder('input with name "email"')).fill('admin@test.com');

    // Type "admin123" into input with name "password"
    await page.getByLabel('input with name "password"').or(page.getByPlaceholder('input with name "password"')).fill('admin123');

    // Click "Sign In"
    await page.getByRole('button', { name: 'Sign In' }).or(page.getByRole('link', { name: 'Sign In' })).click();

    // Assert page contains "Release Command Center"
    await expect(page.getByText('Release Command Center')).toBeVisible();

    // Assert page contains "Audit checkout release gate"
    await expect(page.getByText('Audit checkout release gate')).toBeVisible();

  });
});
