import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-19T11:15:18.334Z

test.describe('Scenario: Run Tests button is present and clickable', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:6000/');

    // Navigate to http://127.0.0.1:6000/
    await page.goto('http://127.0.0.1:6000/');

    // Click "Run Tests"
    await page.getByRole('button', { name: 'Run Tests' }).or(page.getByRole('link', { name: 'Run Tests' })).click();

    // Assert page contains "Tests queued successfully."
    await expect(page.getByText('Tests queued successfully.')).toBeVisible();

  });
});
