import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-02T09:35:57.372Z

test.describe('Scenario 4: Authentication Page Text Verification', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173/auth
    await page.goto('http://localhost:5173/auth');

    // Assert the page contains "a login form"
    await expect(page.getByText('a login form')).toBeVisible();

  });
});
