import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-05-31T18:04:29.158Z

test.describe('Scenario: Navigation works', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to /
    await page.goto('http://localhost:5173/');

    // Click "Settings"
    await page.getByRole('button', { name: 'Settings' }).or(page.getByRole('link', { name: 'Settings' })).click();

    // Assert page contains "Settings"
    await expect(page.getByText('Settings')).toBeVisible();

  });
});
