import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-17T10:18:13.645Z

test.describe('Scenario: Login flow preserves original UI and error handling', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173
    await page.goto('http://localhost:5173');

    // Click "Sign In"
    await page.getByRole('button', { name: 'Sign In' }).or(page.getByRole('link', { name: 'Sign In' })).click();

    // Assert page contains "Sign In"
    await expect(page.getByText('Sign In')).toBeVisible();

    // Assert page contains "Email"
    await expect(page.getByText('Email')).toBeVisible();

    // Assert page contains "Password"
    await expect(page.getByText('Password')).toBeVisible();

    // Assert page contains "Remember me"
    await expect(page.getByText('Remember me')).toBeVisible();

    // Assert page contains "Forgot password?"
    await expect(page.getByText('Forgot password?')).toBeVisible();

  });
});
