import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-02T10:23:29.509Z

test.describe('Scenario 4: Authentication Page Snapshot', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173/auth
    await page.goto('http://localhost:5173/auth');

    // Take a snapshot of the page
    await expect(page).toHaveScreenshot();

  });
});
