import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-02T09:17:04.749Z

test.describe('Scenario: Verify File Tree page renders correctly', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173/tree
    await page.goto('http://localhost:5173/tree');

    // Assert page contains "File Tree — MindFlayer"
    await expect(page.getByText('File Tree — MindFlayer')).toBeVisible();

    // Assert page contains "Hierarchical codebase file tree with comments and code snippets"
    await expect(page.getByText('Hierarchical codebase file tree with comments and code snippets')).toBeVisible();

  });
});
