import { test, expect } from '@playwright/test';

// Auto-generated by MindFlayer Pipeline
// 2026-04-19T11:15:18.335Z

test.describe('Scenario: Login form renders with correct heading and content', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://127.0.0.1:6000/');

    // Navigate to http://127.0.0.1:6000/
    await page.goto('http://127.0.0.1:6000/');

    // Click "Open operations console"
    await page.getByRole('button', { name: 'Open operations console' }).or(page.getByRole('link', { name: 'Open operations console' })).click();

    // Assert page contains "Sign In"
    await expect(page.getByText('Sign In')).toBeVisible();

    // Assert page contains "TestingQA demo target"
    await expect(page.getByText('TestingQA demo target')).toBeVisible();

  });
});
