import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-26T10:29:52.668Z

test.describe('Scenario: Verify landing page title and content', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to `/`
    await page.goto('http://localhost:5173/`/`');

    // Assert page contains "TestingQA"
    await expect(page.getByText('TestingQA')).toBeVisible();

    // Assert page contains "A sample application for validating SentinelQA automated testing pipeline."
    await expect(page.getByText('A sample application for validating SentinelQA automated testing pipeline.')).toBeVisible();

    // Assert page contains "Run Tests" button
    await expect(page.getByText('Run Tests" button')).toBeVisible();

    // Assert page contains "System ready. No tests running." status message
    await expect(page.getByText('System ready. No tests running." status message')).toBeVisible();

  });
});
